version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    links:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27018/chessDatabase

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
